### ISSUE TITLE
Introduce `init` function

### ISSUE THREAD

**Issue by YuhanLiin** [rust-embedded/msp430-rt#14]
Continuation of the discussion from https://github.com/rust-embedded/bare-metal/issues/42. The proposal is to add a new `init` function to the MSP430 runtime that runs before `main`. This allows for the addition of a new attribute that enables interrupts right before `main` runs, since pre-interrupt code can all run in `init`.

I propose that the signature of `init` be `fn init(cs: &CriticalSection) -> Output`, where `Output` can be any user-defined type. If `init` is defined, then the first parameter of `main()` will always be `output: Output`. This allows `init` to pass information to `main` without global variables. The reason why `init` takes `&CriticalSection` instead of `CriticalSection` is so that it can't pass the critical section to `main` via `Output`. We also add a new optional attribute to `main` called `#[enable_interrupt]`, which enables interrupts before `main` runs. If this attribute is present, then the optional `CriticalSection` parameter to `main` is no longer allowed.

**Comment by cr1901** [comment]
@YuhanLiin If we make a release (`0.3.0`) of `msp430`, `msp430-rt` and friends now, with the breaking changes we already made, would adding `init` be considered a further breaking change (thus `0.3.0` -> `0.4.0`) or a backwards-compat change (`0.3.0` -> `0.3.1`)?

If it's a non-breaking change, I would like to add `init` and `#[enable_interrupt]` in a later release. And honestly, even if it _is_ breaking, I think I'd rather do a release now and then go straight to `0.4.0` when ready.

**Comment by YuhanLiin** [comment]
The current proposal should be back-compatible. That might not be the case if we make changes to the design. Are we OK with the current design?

**Comment by cr1901** [comment]
@YuhanLiin Your current design sounds reasonable. I don't _think_ we can get into any "unsoundness in safe code" shenanigans with your proposal. Borrow checker means you can't return a reference from `init` unless it's `'static` or you use `owning_ref`, so that makes things easier.

**Comment by YuhanLiin** [comment]
The only questionable part is that `main` can now have 2 optional parameters, depending on external settings. That can be confusing for users.

**Comment by cr1901** [comment]
I'm also not 100% sure how to implement `init`, since the `#[entry]` macro will need to somehow be aware of the name you're using for the `#[init]` function while the wrapper for `main` is being generated.

From a documentation perspective, I figure that `init` and `entry` could be treated similar to Arduino IDE's `setup()` and `loop()` functions with parameters that make sense for Rust but not for Arduino.

**Comment by YuhanLiin** [comment]
Any examples of something similar out in the wild that we can refer to?

**Comment by cr1901** [comment]
Not that I'm aware of, I'm afraid. I think Arduino is the closest programming environment w/ `setup()`/`loop()`. But that's not Rust :(.

**Comment by YuhanLiin** [comment]
What if we used `pre_init` to implement this feature?

**Comment by cr1901** [comment]
`pre_init` is `unsafe` (rightfully so, because memory isn't initialized yet), and I think we want `init` to be nominally safe?

I personally think `pre_init` probably shouldn't exist down the line, due to the very few guarantees that can be made about the state of your execution environment before memory is initialized. But that's another issue to discuss :D!

**Comment by YuhanLiin** [comment]
We can use `PROVIDE` linker symbols to setup the init function.

**Comment by cr1901** [comment]
This isn't really a huge problem, but I figure it's worth mentioning; the `interrupt_enable`/`pre_interrupt` function macro is not zero cost. Here is an example of code size comparisons for [msp430-quickstart](https://github.com/rust-embedded/msp430-quickstart) before and after I [modified](https://github.com/cr1901/msp430-quickstart/commit/0085983097991c728b770618accc6601eaebf806) the examples (single commit difference) to use the new functionality:

## Before

```
text    data     bss     dec     hex filename
  98       0       0      98      62 debug/msp430g2553-quickstart
  90       0       0      90      5a release/msp430g2553-quickstart
3846       0       2    3848     f08 debug/examples/blinky
 238       0       2     240      f0 release/examples/blinky
1686       0       2    1688     698 debug/examples/override-default-handler
  92       0       2      94      5e release/examples/override-default-handler
6452       0       2    6454    1936 debug/examples/timer-oncecell
 358       0       2     360     168 release/examples/timer-oncecell
5508       0       2    5510    1586 debug/examples/timer-unsafe
 228       0       2     230      e6 release/examples/timer-unsafe
 736       0       6     742     2e6 release/examples/timer
8342       4       8    8354    20a2 release/examples/temp-hal

Binaries which didn't fit:
debug/examples/timer: 2294 18678
debug/examples/temp-hal: 138360 154744
```

## After

```
text    data     bss     dec     hex filename
  98       0       0      98      62 debug/msp430g2553-quickstart
  90       0       0      90      5a release/msp430g2553-quickstart
3846       0       2    3848     f08 debug/examples/blinky
 238       0       2     240      f0 release/examples/blinky
1686       0       2    1688     698 debug/examples/override-default-handler
  92       0       2      94      5e release/examples/override-default-handler
6466       0       2    6468    1944 debug/examples/timer-oncecell
 364       0       2     366     16e release/examples/timer-oncecell
5522       0       2    5524    1594 debug/examples/timer-unsafe
 234       0       2     236      ec release/examples/timer-unsafe
 746       0       6     752     2f0 release/examples/timer
8498       4       8    8510    213e release/examples/temp-hal

Binaries which didn't fit:
debug/examples/timer: 2310 18694
debug/examples/temp-hal: 138456 154840
```

Passing the return value from `pre_interrupt` to `entry` seems to have the biggest effect (`temp-hal`). In fact, the size increase from adding the `pre_interrupt` functionality is worse in the `opt-level=s` `release` profile (156 bytes) compared to the debug profile (96 bytes)! Very interesting...

Nothing worth worrying about right now, just thought it was worth mentioning.

**Comment by YuhanLiin** [comment]
Maybe try forcing `pre_interrupt` to be inlined? Also the "inner" functions generated by the macros should have been made to be inline. In theory if both are inline then the generated code is just one big main function.

**Comment by cr1901** [comment]
`#[inline(always)]` seems to be a net win. With it, most examples shrink back to their original size (if not already the original size). `temp_hal` is still pessimized by 104 bytes, however. Seems that passing data to main isn't zero cost:

```
   text    data     bss     dec     hex filename
     98       0       0      98      62 debug/msp430g2553-quickstart
     90       0       0      90      5a release/msp430g2553-quickstart
   3846       0       2    3848     f08 debug/examples/blinky
    238       0       2     240      f0 release/examples/blinky
   1686       0       2    1688     698 debug/examples/override-default-handler
     92       0       2      94      5e release/examples/override-default-handler
   6352       0       2    6354    18d2 debug/examples/timer-oncecell
    358       0       2     360     168 release/examples/timer-oncecell
   5456       0       2    5458    1552 debug/examples/timer-unsafe
    228       0       2     230      e6 release/examples/timer-unsafe
    736       0       6     742     2e6 release/examples/timer
   8438       4       8    8450    2102 release/examples/temp-hal

Binaries which didn't fit:
debug/examples/timer: 2214 18598
debug/examples/temp-hal: 138280 154664
```

**Comment by YuhanLiin** [comment]
Is the "inner" function inside `entry` being inlined as well? If a new type was introduced to hold the data being passed from `pre_entry` to `entry` then that might be what's causing the slowdown.

**Comment by cr1901** [comment]
`[inline(always)]` on the nested function inside `entry` appears to be a net win (when, and actually generates better code than the "Before" in the above benchmark! Sizes are back to normal; `temp-hal` is 4 bytes bigger, but that's not significant.

## `[inline(always)]` `pre_interrupt` and inner `entry`

```
   text    data     bss     dec     hex filename
     94       0       0      94      5e debug/msp430g2553-quickstart
     90       0       0      90      5a release/msp430g2553-quickstart
   3816       0       2    3818     eea debug/examples/blinky
    234       0       2     236      ec release/examples/blinky
   1682       0       2    1684     694 debug/examples/override-default-handler
     92       0       2      94      5e release/examples/override-default-handler
   6348       0       2    6350    18ce debug/examples/timer-oncecell
    354       0       2     356     164 release/examples/timer-oncecell
   5452       0       2    5454    154e debug/examples/timer-unsafe
    224       0       2     226      e2 release/examples/timer-unsafe
    732       0       6     738     2e2 release/examples/timer
   8346       4       8    8358    20a6 release/examples/temp-hal

Binaries which didn't fit:
debug/examples/timer: 2214 18598
debug/examples/temp-hal: 138264 154648
```

## `[inline(always)]` inner `entry` only

```
   text    data     bss     dec     hex filename
     94       0       0      94      5e debug/msp430g2553-quickstart
     90       0       0      90      5a release/msp430g2553-quickstart
   3816       0       2    3818     eea debug/examples/blinky
    234       0       2     236      ec release/examples/blinky
   1682       0       2    1684     694 debug/examples/override-default-handler
     92       0       2      94      5e release/examples/override-default-handler
   6462       0       2    6464    1940 debug/examples/timer-oncecell
    354       0       2     356     164 release/examples/timer-oncecell
   5518       0       2    5520    1590 debug/examples/timer-unsafe
    224       0       2     226      e2 release/examples/timer-unsafe
    732       0       6     738     2e2 release/examples/timer
   8346       4       8    8358    20a6 release/examples/temp-hal

Binaries which didn't fit:
debug/examples/timer: 2310 18694
debug/examples/temp-hal: 138440 154824
```

It appears most of the savings comes from inlining the inner `entry`.

**Comment by cr1901** [comment]
@YuhanLiin If it's okay with you, I think I want to cut a release. I've confirmed the `msp430-quickstart` examples compile and still work properly.

**Comment by YuhanLiin** [comment]
I think we should do a patch to put `inline[always]` on the inner functions. Then cut a release.

**Comment by cr1901** [comment]
>I think we should do a patch to put inline[always] on the inner functions.

Already done :P

https://github.com/rust-embedded/msp430-rt/commit/647877a0a678344ef6943507c355f1a38d03cad1

**Comment by YuhanLiin** [comment]
I'm also gonna put it on the interrupts

**Comment by YuhanLiin** [comment]
Good to release now, unless we want to decide which attributes to whitelist in our macros.
